/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/archives/[year]/': RouteRecordInfo<'/archives/[year]/', '/archives/:year', { year: ParamValue<true> }, { year: ParamValue<false> }>,
    '/archives/[year]/[month]/': RouteRecordInfo<'/archives/[year]/[month]/', '/archives/:year/:month', { year: ParamValue<true>, month: ParamValue<true> }, { year: ParamValue<false>, month: ParamValue<false> }>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/categories/[...its]': RouteRecordInfo<'/categories/[...its]', '/categories/:its(.*)', { its: ParamValue<true> }, { its: ParamValue<false> }>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/AI-Talk/LLM-talk-0': RouteRecordInfo<'/posts/AI-Talk/LLM-talk-0', '/posts/AI-Talk/LLM-talk-0', Record<never, never>, Record<never, never>>,
    '/posts/AI-Talk/LLM-talk-1': RouteRecordInfo<'/posts/AI-Talk/LLM-talk-1', '/posts/AI-Talk/LLM-talk-1', Record<never, never>, Record<never, never>>,
    '/posts/AI-Talk/LLM-talk-2': RouteRecordInfo<'/posts/AI-Talk/LLM-talk-2', '/posts/AI-Talk/LLM-talk-2', Record<never, never>, Record<never, never>>,
    '/posts/AI-Talk/openvla-reading': RouteRecordInfo<'/posts/AI-Talk/openvla-reading', '/posts/AI-Talk/openvla-reading', Record<never, never>, Record<never, never>>,
    '/posts/Daily-Talk/Dress-Collections': RouteRecordInfo<'/posts/Daily-Talk/Dress-Collections', '/posts/Daily-Talk/Dress-Collections', Record<never, never>, Record<never, never>>,
    '/posts/Daily-Talk/week-1': RouteRecordInfo<'/posts/Daily-Talk/week-1', '/posts/Daily-Talk/week-1', Record<never, never>, Record<never, never>>,
    '/posts/Daily-Talk/week-2': RouteRecordInfo<'/posts/Daily-Talk/week-2', '/posts/Daily-Talk/week-2', Record<never, never>, Record<never, never>>,
    '/posts/Daily-Talk/week-3': RouteRecordInfo<'/posts/Daily-Talk/week-3', '/posts/Daily-Talk/week-3', Record<never, never>, Record<never, never>>,
    '/posts/Daily-Talk/week-4': RouteRecordInfo<'/posts/Daily-Talk/week-4', '/posts/Daily-Talk/week-4', Record<never, never>, Record<never, never>>,
    '/posts/Daily-Talk/week-5': RouteRecordInfo<'/posts/Daily-Talk/week-5', '/posts/Daily-Talk/week-5', Record<never, never>, Record<never, never>>,
    '/posts/Daily-Talk/week-6': RouteRecordInfo<'/posts/Daily-Talk/week-6', '/posts/Daily-Talk/week-6', Record<never, never>, Record<never, never>>,
    '/posts/Tech-Talk/Git-Tutorial': RouteRecordInfo<'/posts/Tech-Talk/Git-Tutorial', '/posts/Tech-Talk/Git-Tutorial', Record<never, never>, Record<never, never>>,
    '/posts/Tech-Talk/Github-Actions-and-Pages-Tutorials': RouteRecordInfo<'/posts/Tech-Talk/Github-Actions-and-Pages-Tutorials', '/posts/Tech-Talk/Github-Actions-and-Pages-Tutorials', Record<never, never>, Record<never, never>>,
    '/posts/Tech-Talk/Isaac-Sim-Notes': RouteRecordInfo<'/posts/Tech-Talk/Isaac-Sim-Notes', '/posts/Tech-Talk/Isaac-Sim-Notes', Record<never, never>, Record<never, never>>,
    '/posts/Tech-Talk/Obsidian-Tutorial': RouteRecordInfo<'/posts/Tech-Talk/Obsidian-Tutorial', '/posts/Tech-Talk/Obsidian-Tutorial', Record<never, never>, Record<never, never>>,
    '/posts/Tech-Talk/RM-Memories': RouteRecordInfo<'/posts/Tech-Talk/RM-Memories', '/posts/Tech-Talk/RM-Memories', Record<never, never>, Record<never, never>>,
    '/posts/Tech-Talk/RM-Tutorial-Section-1': RouteRecordInfo<'/posts/Tech-Talk/RM-Tutorial-Section-1', '/posts/Tech-Talk/RM-Tutorial-Section-1', Record<never, never>, Record<never, never>>,
    '/posts/Tech-Talk/RM-Tutorial-Section-2': RouteRecordInfo<'/posts/Tech-Talk/RM-Tutorial-Section-2', '/posts/Tech-Talk/RM-Tutorial-Section-2', Record<never, never>, Record<never, never>>,
    '/posts/Tech-Talk/RM-Tutorial-Section-3': RouteRecordInfo<'/posts/Tech-Talk/RM-Tutorial-Section-3', '/posts/Tech-Talk/RM-Tutorial-Section-3', Record<never, never>, Record<never, never>>,
    '/posts/Tech-Talk/Strange-Bugs': RouteRecordInfo<'/posts/Tech-Talk/Strange-Bugs', '/posts/Tech-Talk/Strange-Bugs', Record<never, never>, Record<never, never>>,
    '/posts/Tech-Talk/VitePress-Tutorial': RouteRecordInfo<'/posts/Tech-Talk/VitePress-Tutorial', '/posts/Tech-Talk/VitePress-Tutorial', Record<never, never>, Record<never, never>>,
    '/posts/Tech-Talk/vpn-setting': RouteRecordInfo<'/posts/Tech-Talk/vpn-setting', '/posts/Tech-Talk/vpn-setting', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
    '/tags/[tag]/': RouteRecordInfo<'/tags/[tag]/', '/tags/:tag', { tag: ParamValue<true> }, { tag: ParamValue<false> }>,
  }
}
